version: '2.1'

services:

    # Project Name #
    gdm-replicator:
        build:
            dockerfile: docker/Dockerfile
        container_name: gdm-replicator
        links:
            - gdm-replicator-ruby

    gdm-replicator-ruby:
        build:
            dockerfile: docker/ruby/Dockerfile
        container_name: gdm-replicator-ruby
        links:
            - gdm-replicator-redis

    gdm-replicator-redis:
        build:
          dockerfile: docker/redis/Dockerfile
        container_name: gdm-replicator-redis