---

# Config of brokers
#
# Structure is
# :BROKER_NAME
#   :platforms
#     :PLATFORM_NAME : [ARRAY OF SERVERS]
#

:gdm:
  :platforms:
    :mt4: [live20, live21]
    :trado: [live20]

:special:
  :platforms:
    :special: [special]